### ISSUE TITLE
Samsung N900 Android 4.3 Selinux in enforcing

### ISSUE THREAD

**Issue by ZeevR** [koush/Superuser#227]
su does not work in on the Samsung SM-N900 stock 4.3 ROM.
SU version 15 from superuser.zip installed via recovery.
logcat contains the following:
D/su      (11540): su invoked.
D/su      (11540): starting daemon client 2000 0
E/su      (11540): outfd /dev/com.koushikdutta.superuser.daemon/11540.stdout  failed with 13: Permission denied

chainfire su does work on the same setup.

After several attempts ps is filled with su daemons.
A notification shows saying "Security information: an application attempted to access system on your device without authorisation. This attempt has been blocked. Changing your security level to normal may solve this problem. Deleting applications obtained from unauthorised sources may improve security".

I think this may be related to the daemon improperly avoiding CONFIG_SEC_RESTRICT_FORK shenanigans.

**Comment by koush** [comment]
will release an update, i think this is fixed.

**Comment by mohankr** [comment]
Hi, is the fix incorporated? I took the latest source pull as of today. Still get the permission denied on Samsung JB 4.3 roms with Stock Kernel (with the RESTRICT_FORK stuff). Thanks

**Comment by koush** [comment]
It should be, I thought this was the fix.

https://github.com/koush/Superuser/blob/master/Superuser/jni/su/su.c#L643

I'm not familiar with the underlying issue though.

**Comment by mohankr** [comment]
Hi Koush,
  The Stock Samsung Kernel's in JB 4.3 are by default SELinux Enforcing (apart from the setuid restrictions), as a side note if I run the SELinux permissive kernel, then everything is fine. But with enforcing mode, the client cannot connect to the unix domain socket, it fails with the error above in the original poster. Not sure why the permissions appear to be there, wonder if there is some policy restrictions. ChainFire Su daemon does not have that issue though..Here is the socket permissions
I believe the comments in issue are related
https://github.com/koush/Superuser/issues/228

It might mean that we might need to create the socket file somewhere else than dev?

 /system/bin/ls -Z /dev/com.koushikdutta.superuser.daemon/server
srwxrwxrwx root     root              u:object_r:device:s0 server

**Comment by ZeevR** [comment]
From a few tests I've done this fix: https://github.com/koush/Superuser/blob/master/Superuser/jni/su/su.c#L643
Does not solve the issue.
I'm looking into it.

**Comment by mohankr** [comment]
I think I have a fix I am testing it works good till now. I will fork and commit and see if that is acceptable.

**Comment by mohankr** [comment]
Submitted a pull request for SELinux Enforcing systems, I have tested it for a week now and works flawlessly on my end on a Samsung 4.3 stock kernel
