### ISSUE TITLE
'su' does not run on Nexus 5/Lollipop - only position independent executables (PIE) are supported

### ISSUE THREAD

**Issue by RunasSudo** [koush/Superuser#268]
Clicking Recovery/Install gives ‘There was an error installing Superuser. Please send a log of the error to the developer.’ Manually installing the `su` binary and attempting to run it gives:
`error: only position independent executables (PIE) are supported.`

**Comment by RunasSudo** [comment]
Well, I compiled `su` from source targeting `android-21`, and I ended up with a binary that works in ADB but crashes in Terminal Emulator with

```
I/ActivityManager(  786): START u0 {flg=0x10800000 cmp=com.koushikdutta.superuser/.MultitaskSuRequestActivity (has extras)} from uid 10109 on display 0
W/Thread-568( 5781): type=1400 audit(0.0:16): avc: denied { write } for name=".socket5763" dev="tmpfs" ino=37344 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:device:s0 tclass=sock_file
I/Superuser( 5630): Permission denied
I/Superuser( 5630): java.io.IOException: Permission denied
I/Superuser( 5630):     at android.net.LocalSocketImpl.connectLocal(Native Method)
I/Superuser( 5630):     at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:290)
I/Superuser( 5630):     at android.net.LocalSocket.connect(LocalSocket.java:130)
I/Superuser( 5630):     at com.koushikdutta.superuser.MultitaskSuRequestActivity$8.run(MultitaskSuRequestActivity.java:306)
```

I'll leave this one to the experts.

**Comment by jazzrz86** [comment]
The problem is, even if you are root, you are still effectively running in the shell or untrusted_app context. SElinux will stop you from doing anything. SU will need to have the policy adjustments alongside root- and it is a huge effort compared to previous Android.

The current root solution (SuperSU from ChainsDD) spawns from the zygote context and still requires a supporting binary to adjust the SElinux policies.

**Comment by leesah** [comment]
Does this mean Lollipop cannot be rooted as previous versions and it's pointless to install any of the three alternatives in Play store?

**Comment by sparkym3** [comment]
No that is not what it means. Lollipop is rootable and superSU is a great working version (though not open source).

**Comment by leesah** [comment]
Thanks @sparkym3 for answering. So is there an uninstallation guide for koush/Superuser? Cuz I didn't see one mentioned in the README.md, and I have installed via the recovery zip.

**Comment by mschewe** [comment]
So if there is now way to run Superuser on Lollipop devices this is the end of the OpenSource su project? How could I adjust SElinux policies if I make my own image?

**Comment by CHEF-KOCH** [comment]
SuperSU works on Lollipop even if the bootloader is locked and all is stock like the recovery. Since /data/local isn't protected you can just copy all stuff in there and execute them. I tried this on my friends LG G3 and it works perfect (should works on all phones! and ROMS!).

Original source is [here](http://blog.lvu.kr/g2-lollipop-%EC%88%9C%EC%A0%95-%EB%A3%A8%ED%8C%85/) and an XDA thread can be found [here](http://forum.xda-developers.com/android/development/guide-root-method-lg-devices-t3049772).

**Comment by phhusson** [comment]
This issue should actually be closed, because it's been fixed by https://github.com/koush/Superuser/commit/5291f21e9ce5224a20b25a80d8978afbaa19bb66

**Comment by phhusson** [comment]
It even works properly on a MTK Android 5.0, assuming proper SELinux setting. (namely, I disabled SELInux)

**Comment by ildar** [comment]
would you make a release with the fix?
and, BTW, F-Droid still doesn't have the working version for Loli

**Comment by valiolichev** [comment]
This is SONY XPERIA Z2 D 6503
На 25.07.2015 г. 20:46 "ildar" notifications@github.com написа:

**Comment by phhusson** [comment]
For interested users, I'm working on an opensource Superuser, fork of Koush's SU, which I intent to be compatible with Chainfire's command options. Any help would be much appreciated. (I already have most SELinux knowledge needed, and working PoC for boot)

**Comment by valiolichev** [comment]
WHAT IS THIS "PIE".,BUT MY PHONE IS NOT NEXUS.,MY PHONE IS XPERIA Z2 D6503
На 27.07.2015 г. 21:18 "Pierre-Hugues HUSSON" notifications@github.com
написа:

**Comment by jeekajoo** [comment]
@phhusson :+1: this is great. I cannot help you but well I support
